// Downloads the bundled display fonts (OFL licensed) from Google Fonts into
// public/fonts/ and writes src/ui/styles/fonts.css with local @font-face rules.
// The Korean face is kept as Google's unicode-range slices, so a page only
// loads the slices it actually uses. Run with: node scripts/fetch-fonts.mjs
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

const FONTS = [
  { dir: 'cinzel', family: 'Cinzel', query: 'Cinzel:wght@400..900' },
  { dir: 'hahmlet', family: 'Hahmlet', query: 'Hahmlet:wght@700' },
]

let css = `/* Bundled fonts (generated by scripts/fetch-fonts.mjs; licenses in public/fonts/<name>/OFL.txt). */\n`
let total = 0
for (const font of FONTS) {
  mkdirSync(join(root, 'public/fonts', font.dir), { recursive: true })
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${font.query}&display=swap`, {
    headers: { 'User-Agent': UA },
  })
  const text = await res.text()
  const blocks = text.match(/@font-face\s*\{[^}]*\}/g) ?? []
  let i = 0
  for (const block of blocks) {
    const url = block.match(/url\(([^)]+)\)/)?.[1]
    const weight = block.match(/font-weight:\s*([^;]+);/)?.[1] ?? '400'
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]
    if (!url) continue
    i += 1
    const name = `${font.dir}-${weight.replace(/\s+/g, '-')}-${String(i).padStart(3, '0')}.woff2`
    const data = Buffer.from(await (await fetch(url)).arrayBuffer())
    writeFileSync(join(root, 'public/fonts', font.dir, name), data)
    total += data.length
    css += `@font-face{font-family:'${font.family}';font-style:normal;font-weight:${weight};font-display:swap;src:url('/fonts/${font.dir}/${name}') format('woff2');${range ? `unicode-range:${range};` : ''}}\n`
  }
  console.log(`${font.family}: ${i} files`)
}
writeFileSync(join(root, 'src/ui/styles/fonts.css'), css)
console.log(`total ${(total / 1024).toFixed(0)} KB`)
